In [1]:
%%sql
use prod_db

Empty DataFrame
Columns: []
Index: []

In [2]:
%%sql
show catalogs;

         catalog
0          local
1  spark_catalog

In [4]:
%%sql
show schemas IN local;

-- Catalog -> schema

  namespace
0      prod
1   prod_db

In [6]:
%%sql 
show tables IN prod_db
-- schema -> Table

  namespace tableName  isTemporary
0   prod_db    orders        False
1   prod_db  partsupp        False
2   prod_db  supplier        False
3   prod_db    nation        False
4   prod_db  lineitem        False
5   prod_db  customer        False
6   prod_db      part        False
7   prod_db    region        False

In [7]:
%%sql --show
select * from prod_db.customer limit 2

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,1,Customer#000000001,"IVhzIApeRb ot,c,E",15,25-989-741-2988,711.56,BUILDING,"to the even, regular platelets. regular, ironi..."
1,2,Customer#000000002,"XSTf4,NCwDVaWNe6tEgvwfmRchLXak",13,23-768-687-3665,121.65,AUTOMOBILE,l accounts. blithely ironic theodolites integr...

In [8]:
%%sql 
DESCRIBE lineitem

           col_name      data_type comment
0        l_orderkey         bigint    None
1         l_partkey         bigint    None
2         l_suppkey         bigint    None
3      l_linenumber            int    None
4        l_quantity  decimal(15,2)    None
5   l_extendedprice  decimal(15,2)    None
6        l_discount  decimal(15,2)    None
7             l_tax  decimal(15,2)    None
8      l_returnflag         string    None
9      l_linestatus         string    None
10       l_shipdate           date    None
11     l_commitdate           date    None
12    l_receiptdate           date    None
13   l_shipinstruct         string    None
14       l_shipmode         string    None
15        l_comment         string    None

In [9]:
%%sql
DESCRIBE extended lineitem

,col_name,data_type,comment
0,l_orderkey,bigint,NaN
1,l_partkey,bigint,NaN
2,l_suppkey,bigint,NaN
3,l_linenumber,int,NaN
4,l_quantity,"decimal(15,2)",NaN
5,l_extendedprice,"decimal(15,2)",NaN
6,l_discount,"decimal(15,2)",NaN
7,l_tax,"decimal(15,2)",NaN
8,l_returnflag,string,NaN
9,l_linestatus,string,NaN
10,l_shipdate,date,NaN
11,l_commitdate,date,NaN
12,l_receiptdate,date,NaN
13,l_shipinstruct,string,NaN
14,l_shipmode,string,NaN
15,l_comment,string,NaN
16,,,
17,# Metadata Columns,,
18,_spec_id,int,
19,_partition,struct<>,
20,_file,string,
21,_pos,bigint,
22,_deleted,boolean,
23,,,
24,# Detailed Table Information,,
25,Name,local.prod_db.lineitem,
26,Type,MANAGED,
27,Location,file:///home/airflow/warehouse/prod_db/lineitem,
28,Provider,iceberg,
29,Owner,root,
30,Table Properties,"[current-snapshot-id=2312571846575296794,forma...",
31,Statistics,"103298384 bytes, 600572 rows",NaN

In [11]:
%%sql
-- use * to specify all columns
SELECT * FROM orders Limit 4

,o_orderkey,o_custkey,o_orderstatus,o_totalprice,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_comment
0,1,3691,O,194029.55,1996-01-02,5-LOW,Clerk#000000951,0,nstructions sleep furiously among
1,2,7801,O,60951.63,1996-12-01,1-URGENT,Clerk#000000880,0,"foxes. pending accounts at the pending, silen..."
2,3,12332,F,247296.05,1993-10-14,5-LOW,Clerk#000000955,0,sly final accounts boost. carefully regular id...
3,4,13678,O,53829.87,1995-10-11,5-LOW,Clerk#000000124,0,"sits. slyly regular warthogs cajole. regular, ..."

In [12]:
%%sql
Select o_orderkey, o_totalprice FROM orders LIMIT 4

   o_orderkey o_totalprice
0           1    194029.55
1           2     60951.63
2           3    247296.05
3           4     53829.87

In [13]:
%%sql 
-- all customer rows that have c_nationkey = 20
SELECT * FROM customer WHERE c_nationkey = 20 LIMIT 10;

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,6,Customer#000000006,"sKZz0CsnMD7mp4Xd0YrBvx,LREYKUWAh yVn",20,30-114-968-4951,7638.57,AUTOMOBILE,tions. even deposits boost according to the sl...
1,81,Customer#000000081,SH6lPA7JiiNC6dNTrR,20,30-165-277-3269,2023.71,BUILDING,r packages. fluffily ironic requests cajole fl...
2,100,Customer#000000100,fptUABXcmkC5Wx,20,30-749-445-4907,9889.89,FURNITURE,"was furiously fluffily quiet deposits. silent,..."
3,210,Customer#000000210,13cFL9sG1nrGERURN9WZI0,20,30-876-248-9750,7250.14,HOUSEHOLD,nusual instructions sleep regular acc
4,223,Customer#000000223,"ftau6Pk,brboMyEl,,kFm",20,30-193-643-1517,7476.20,BUILDING,"al, regular requests run furiously blithely si..."
5,228,Customer#000000228,A1Zvuxjdpt8TZP6i41H3fn9csGqOJUm5x0NIS1LA,20,30-435-915-1603,6868.12,FURNITURE,blithely ironic theodolites
6,247,Customer#000000247,N8q4W4QQG2mHY47Dg6,20,30-151-905-3513,8495.92,HOUSEHOLD,es affix furiously regular deposits. blithely ...
7,278,Customer#000000278,4jqLjG 2aeYMFEJi,20,30-445-570-5841,7621.56,BUILDING,"pending, express requests cajole carefully sp..."
8,285,Customer#000000285,ApUL7bgFMUXGXewpoQyQOSnLeL9Vc1rrkW,20,30-235-130-1313,7276.72,FURNITURE,dolphins after the slyly ironic packages boost...
9,321,Customer#000000321,"g3,8g XHACSvjZtJuiNk5BYiyPFnIxg",20,30-114-675-9153,7718.77,FURNITURE,special requests! express dugouts can affix fu...

In [14]:
%%sql
-- all customer rows that have c_nationkey = 20 and c_acctbal > 1000
SELECT * FROM customer WHERE c_nationkey = 20 AND c_acctbal > 1000 LIMIT 10;

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,6,Customer#000000006,"sKZz0CsnMD7mp4Xd0YrBvx,LREYKUWAh yVn",20,30-114-968-4951,7638.57,AUTOMOBILE,tions. even deposits boost according to the sl...
1,81,Customer#000000081,SH6lPA7JiiNC6dNTrR,20,30-165-277-3269,2023.71,BUILDING,r packages. fluffily ironic requests cajole fl...
2,100,Customer#000000100,fptUABXcmkC5Wx,20,30-749-445-4907,9889.89,FURNITURE,"was furiously fluffily quiet deposits. silent,..."
3,210,Customer#000000210,13cFL9sG1nrGERURN9WZI0,20,30-876-248-9750,7250.14,HOUSEHOLD,nusual instructions sleep regular acc
4,223,Customer#000000223,"ftau6Pk,brboMyEl,,kFm",20,30-193-643-1517,7476.20,BUILDING,"al, regular requests run furiously blithely si..."
5,228,Customer#000000228,A1Zvuxjdpt8TZP6i41H3fn9csGqOJUm5x0NIS1LA,20,30-435-915-1603,6868.12,FURNITURE,blithely ironic theodolites
6,247,Customer#000000247,N8q4W4QQG2mHY47Dg6,20,30-151-905-3513,8495.92,HOUSEHOLD,es affix furiously regular deposits. blithely ...
7,278,Customer#000000278,4jqLjG 2aeYMFEJi,20,30-445-570-5841,7621.56,BUILDING,"pending, express requests cajole carefully sp..."
8,285,Customer#000000285,ApUL7bgFMUXGXewpoQyQOSnLeL9Vc1rrkW,20,30-235-130-1313,7276.72,FURNITURE,dolphins after the slyly ironic packages boost...
9,321,Customer#000000321,"g3,8g XHACSvjZtJuiNk5BYiyPFnIxg",20,30-114-675-9153,7718.77,FURNITURE,special requests! express dugouts can affix fu...

In [16]:
%%sql
-- all customer rows that have c_nationkey = 20 or c_acctbal > 1000
SELECT * FROM customer where c_nationkey = 20 OR c_acctbal > 1000 LIMIT 10;

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,3,Customer#000000003,MG9kdTD2WBHm,1,11-719-748-3364,7498.12,AUTOMOBILE,"deposits eat slyly ironic, even instructions...."
1,4,Customer#000000004,XxVSJsLAGtn,4,14-128-190-5944,2866.83,MACHINERY,"requests. final, regular ideas sleep final accou"
2,6,Customer#000000006,"sKZz0CsnMD7mp4Xd0YrBvx,LREYKUWAh yVn",20,30-114-968-4951,7638.57,AUTOMOBILE,tions. even deposits boost according to the sl...
3,7,Customer#000000007,TcGe5gaZNgVePxU5kRrvXBfkasDTea,18,28-190-982-9759,9561.95,AUTOMOBILE,"ainst the ironic, express theodolites. express..."
4,8,Customer#000000008,"I0B10bB0AymmC, 0PrRYBCP1yGJ8xcBPmWhl5",17,27-147-574-9335,6819.74,BUILDING,among the slyly regular theodolites kindle bli...
5,9,Customer#000000009,xKiAFTjUsCuxfeleNqefumTrjS,8,18-338-906-3675,8324.07,FURNITURE,r theodolites according to the requests wake t...
6,10,Customer#000000010,6LrEaV6KR6PLVcgl2ArL Q3rqzLzcT1 v2,5,15-741-346-9870,2753.54,HOUSEHOLD,es regular deposits haggle. fur
7,12,Customer#000000012,9PWKuhzT4Zr1Q,13,23-791-276-1263,3396.49,HOUSEHOLD,to the carefully final braids. blithely regul...
8,13,Customer#000000013,nsXQu0oVjD7PM659uC3SRSp,3,13-761-547-5974,3857.34,BUILDING,ounts sleep carefully after the close frays. c...
9,14,Customer#000000014,KXkletMlL2JQEA,1,11-845-129-3851,5266.30,FURNITURE,", ironic packages across the unus"

In [17]:
%%sql
-- all customer rows that have (c_nationkey = 20 and c_acctbal > 1000) or rows that have c_nationkey = 11
SELECT * FROM customer WHERE ( c_nationkey = 20 AND c_acctbal > 1000 ) OR c_nationkey = 11 LIMIT 10;

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,6,Customer#000000006,"sKZz0CsnMD7mp4Xd0YrBvx,LREYKUWAh yVn",20,30-114-968-4951,7638.57,AUTOMOBILE,tions. even deposits boost according to the sl...
1,52,Customer#000000052,7 QOqGqqSy9jfV51BC71jcHJSD0,11,21-186-284-5998,5630.28,HOUSEHOLD,ic platelets use evenly even accounts. stealth...
2,81,Customer#000000081,SH6lPA7JiiNC6dNTrR,20,30-165-277-3269,2023.71,BUILDING,r packages. fluffily ironic requests cajole fl...
3,84,Customer#000000084,lpXz6Fwr9945rnbtMc8PlueilS1WmASr CB,11,21-546-818-3802,5174.71,FURNITURE,ly blithe foxes. special asymptotes haggle bli...
4,100,Customer#000000100,fptUABXcmkC5Wx,20,30-749-445-4907,9889.89,FURNITURE,"was furiously fluffily quiet deposits. silent,..."
5,131,Customer#000000131,"jyN6lAjb1FtH10rMC,XzlWyCBrg75",11,21-840-210-3572,8595.53,HOUSEHOLD,jole special packages. furiously final depende...
6,134,Customer#000000134,sUiZ78QCkTQPICKpA9OBzkUp2FM,11,21-200-159-5932,4608.90,BUILDING,yly fluffy foxes boost final ideas. b
7,148,Customer#000000148,BhSPlEWGvIJyT9swk vCWE,11,21-562-498-6636,2135.60,HOUSEHOLD,ing to the carefully ironic requests. carefull...
8,190,Customer#000000190,"F2X,GhSqLz8k u0gWsirsraFaEDEo6vIGtOTaO1T",11,21-730-373-8193,1657.46,AUTOMOBILE,uickly-- fluffily pending instructions boo
9,210,Customer#000000210,13cFL9sG1nrGERURN9WZI0,20,30-876-248-9750,7250.14,HOUSEHOLD,nusual instructions sleep regular acc

In [18]:
%%sql
-- all customer rows where the name has a 381 in it 
SELECT * FROM customer WHERE c_name LIKE '%381%';

-- % zero or more characters, _ any single characters

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,381,Customer#000000381,w3zVseYDbjBbzLld,5,15-860-208-7093,9931.71,BUILDING,"t regular, bold accounts. carefully quick pack..."
1,1381,Customer#000001381,HqKfFUD6Ib9yoFM5cIgMxjXaqdJAyKSN5w Od,22,32-418-900-6494,367.82,BUILDING,foxes thrash slyly express foxes. even th
2,2381,Customer#000002381,tTpWXo1T9kGGKmIY2Q3Lu0qvY91MB2y wiiXZnC,5,15-493-990-8133,412.99,FURNITURE,s sublate near the fluffily even accounts. car...
3,3381,Customer#000003381,0YH6fHB57ESYMg4ZWEMiI,13,23-441-750-5088,2473.54,AUTOMOBILE,usly. final accounts haggle quickly regular re...
4,3810,Customer#000003810,KF97idWMWjeQJOSrrn,18,28-881-994-8196,9906.80,FURNITURE,ajole quickly whithout the final
5,3811,Customer#000003811,QUwmhBILqK9PkJs8v7s,22,32-962-997-2221,5697.04,FURNITURE,lar dependencies. quickly special ideas nod bl...
6,3812,Customer#000003812,kk2BVO1yFq,14,24-653-654-5032,4204.53,FURNITURE,"uses about the special, even ideas"
7,3813,Customer#000003813,"rMGt,nD,hcW5Zs9Ll1RmxoOp4R7E4",6,16-983-191-7833,-494.03,HOUSEHOLD,ing packages integrate slyly ironic accounts. u
8,3814,Customer#000003814,maXF4pqXsDDCOX8s8EnoMvANDX9R,20,30-833-732-5401,-207.83,AUTOMOBILE,beans alongside of the slyly silent a
9,3815,Customer#000003815,9V8i6Nnox5dg971B1VeWpo,19,29-968-870-7672,2887.99,FURNITURE,gside of the slyly special requests sleep q
10,3816,Customer#000003816,HlfxRo283j,6,16-806-750-3968,4353.05,AUTOMOBILE,ly regular requests. excuses cajole carefully ...
11,3817,Customer#000003817,j4BW LuK9ux6MjgZuy3S9mLk2Fj2 opBPpv4E,16,26-142-669-5787,9766.42,AUTOMOBILE,quests along the requests cajole doggedly with...
12,3818,Customer#000003818,u woSkI6h5pzxTeuljOt8OEqb0eKm4EC3aK8qsXU,7,17-983-218-3716,346.99,AUTOMOBILE,"refully bold, ironic deposits. unusual pinto b..."
13,3819,Customer#000003819,8MHu8GRkZQmZu,4,14-964-709-5782,-210.31,BUILDING,y alongside of the furiously ironic theodolite...
14,4381,Customer#000004381,fia3jW4U1zyBVO53Loy4yBIhyLI,2,12-570-797-1472,2542.55,HOUSEHOLD,le blithely express courts. silent theodol
15,5381,Customer#000005381,"Q3a0gyIKhp,Dq83eTXbnwdcw3piGBV",5,15-700-184-7619,4130.88,MACHINERY,"posits cajole slyly pending requests. special,..."
16,6381,Customer#000006381,"qgLG,UnydWWKKYvXEe6g,",7,17-877-502-9214,7346.88,HOUSEHOLD,onic instructions wake furiously according to ...
17,7381,Customer#000007381,uAT93aEOFo7IUvh BMFgRm48hsr7LtPfQJ,20,30-666-139-1602,73.39,BUILDING,"s. regular, quiet asymptotes haggle. carefully..."
18,8381,Customer#000008381,UGPKSwMKPKlEKI4TcaW8QhSOCG3FU CpEjxOh,0,10-177-308-9094,6674.59,AUTOMOBILE,ies wake. furiously even packages detect caref...
19,9381,Customer#000009381,qJ3cnPmcBveKU,17,27-708-588-6706,4788.15,HOUSEHOLD,ipliers cajole carefully about the regularly e...
20,10381,Customer#000010381,afn8 WhcegXV,15,25-294-314-6077,106.15,FURNITURE,aggle braids. fluffily unusual deposits are fu...
21,11381,Customer#000011381,PjOaghnkD4gPAWSd,7,17-652-294-7849,1959.81,MACHINERY,al packages. carefully express sentiments run sl
22,12381,Customer#000012381,Kb62OK5MAGNfoZapzkh3mVlHUbnaJGO,13,23-989-969-2819,1172.56,HOUSEHOLD,boost fluffily under the carefully final plat...
23,13381,Customer#000013381,8GqvnMJMlWkXKRj,9,19-465-107-1496,3221.83,HOUSEHOLD,cajole slyly fluffily regular theodolites. fu...
24,13810,Customer#000013810,hnBypav 8dLiLA5708IY EkglglIu,18,28-953-486-1222,5133.48,BUILDING,nts x-ray quickly ironic dependencies. final f...
25,13811,Customer#000013811,4wQHIBhPlpR2SiLHibQDiMnD QQ,19,29-964-589-6640,3436.54,MACHINERY,uses wake fluffily among the final requests. s...
26,13812,Customer#000013812,"5xe,ec0dYY8bHxjE6snPPthlSVLGtODQSfTvbzgg",0,10-571-845-2630,5982.87,AUTOMOBILE,taphs wake doggedly. regular deposits are ruth...
27,13813,Customer#000013813,4JVzQJ3khGxVrFf,21,31-140-142-6191,1190.11,MACHINERY,. slyly ironic requests cajole. fluffily regul...
28,13814,Customer#000013814,"cDzPoXmdThX71X,stbbFjSuJ",17,27-767-457-2550,2131.39,FURNITURE,the quickly unusual requests try to sleep acr...
29,13815,Customer#000013815,7j3tuteedv6rNi9rkC,11,21-606-813-1389,4240.37,FURNITURE,are slyly along the regular packages. fluffily...
30,13816,Customer#000013816,43rdFKy0VFoUw CdoTVAr8r,17,27-501-367-6604,7844.29,AUTOMOBILE,al deposits haggle carefully blithely regular ...
31,13817,Customer#000013817,NKZKVqAO6ecAwktSC2TPI5MTDIUdzj,3,13-978-449-6295,2094.32,FURNITURE,sual platelets. fluffily regular asymptotes ar...
32,13818,Customer#000013818,AZTdLT2SIfMpgikcUsh6A4FVgYK,15,25-948-173-6359,8239.56,HOUSEHOLD,he ironic packages. quickly ironic packages al...
33,13819,Customer#000013819,SeFlzJiz5dA57SHig9BX0wi85WzdN3rvi7SWlS8r,12,22-868-584-6588,1312.29,BUILDING,ake excuses. quickly final ideas acros
34,14381,Customer#000014381,"IQGxdTky,8idm",21,31-449-680-6297,1915.30,FURNITURE,across the slyly ironic requests; regular brai...

In [19]:
%%sql
-- all customer rows where the name ends with a 381
SELECT * FROM customer WHERE c_name LIKE '%381';

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,381,Customer#000000381,w3zVseYDbjBbzLld,5,15-860-208-7093,9931.71,BUILDING,"t regular, bold accounts. carefully quick pack..."
1,1381,Customer#000001381,HqKfFUD6Ib9yoFM5cIgMxjXaqdJAyKSN5w Od,22,32-418-900-6494,367.82,BUILDING,foxes thrash slyly express foxes. even th
2,2381,Customer#000002381,tTpWXo1T9kGGKmIY2Q3Lu0qvY91MB2y wiiXZnC,5,15-493-990-8133,412.99,FURNITURE,s sublate near the fluffily even accounts. car...
3,3381,Customer#000003381,0YH6fHB57ESYMg4ZWEMiI,13,23-441-750-5088,2473.54,AUTOMOBILE,usly. final accounts haggle quickly regular re...
4,4381,Customer#000004381,fia3jW4U1zyBVO53Loy4yBIhyLI,2,12-570-797-1472,2542.55,HOUSEHOLD,le blithely express courts. silent theodol
5,5381,Customer#000005381,"Q3a0gyIKhp,Dq83eTXbnwdcw3piGBV",5,15-700-184-7619,4130.88,MACHINERY,"posits cajole slyly pending requests. special,..."
6,6381,Customer#000006381,"qgLG,UnydWWKKYvXEe6g,",7,17-877-502-9214,7346.88,HOUSEHOLD,onic instructions wake furiously according to ...
7,7381,Customer#000007381,uAT93aEOFo7IUvh BMFgRm48hsr7LtPfQJ,20,30-666-139-1602,73.39,BUILDING,"s. regular, quiet asymptotes haggle. carefully..."
8,8381,Customer#000008381,UGPKSwMKPKlEKI4TcaW8QhSOCG3FU CpEjxOh,0,10-177-308-9094,6674.59,AUTOMOBILE,ies wake. furiously even packages detect caref...
9,9381,Customer#000009381,qJ3cnPmcBveKU,17,27-708-588-6706,4788.15,HOUSEHOLD,ipliers cajole carefully about the regularly e...
10,10381,Customer#000010381,afn8 WhcegXV,15,25-294-314-6077,106.15,FURNITURE,aggle braids. fluffily unusual deposits are fu...
11,11381,Customer#000011381,PjOaghnkD4gPAWSd,7,17-652-294-7849,1959.81,MACHINERY,al packages. carefully express sentiments run sl
12,12381,Customer#000012381,Kb62OK5MAGNfoZapzkh3mVlHUbnaJGO,13,23-989-969-2819,1172.56,HOUSEHOLD,boost fluffily under the carefully final plat...
13,13381,Customer#000013381,8GqvnMJMlWkXKRj,9,19-465-107-1496,3221.83,HOUSEHOLD,cajole slyly fluffily regular theodolites. fu...
14,14381,Customer#000014381,"IQGxdTky,8idm",21,31-449-680-6297,1915.30,FURNITURE,across the slyly ironic requests; regular brai...

In [20]:
%%sql
-- all customer rows where the name starts with a 381
SELECT * FROM customer WHERE c_name LIKE '381%';

Empty DataFrame
Columns: [c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment]
Index: []

In [21]:
%%sql
-- all customer rows where the name has a combination of any character and 9 and 1
SELECT * FROM customer WHERE c_name LIKE '%_81%';

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,81,Customer#000000081,SH6lPA7JiiNC6dNTrR,20,30-165-277-3269,2023.71,BUILDING,r packages. fluffily ironic requests cajole fl...
1,181,Customer#000000181,YNviWd WrRkZvSw1OxIewBq,9,19-653-305-8440,3929.96,FURNITURE,final requests cajole furiously acro
2,281,Customer#000000281,x5gJ8IGm2Fo9Jigt,6,16-809-382-6446,4361.70,BUILDING,fully quiet ideas detect quickly even packages...
3,381,Customer#000000381,w3zVseYDbjBbzLld,5,15-860-208-7093,9931.71,BUILDING,"t regular, bold accounts. carefully quick pack..."
4,481,Customer#000000481,"o4xa7J20NqHM8E0ykH,NKe1gPz04OqIn",21,31-363-392-6461,7157.21,FURNITURE,"s can nag slyly instructions. regular, regular..."
...,...,...,...,...,...,...,...,...
394,14817,Customer#000014817,"F8 IqOYpHOy,Lmi5sVroUjyfa9",23,33-274-524-2558,4203.42,FURNITURE,ests are. carefully pending platelets integrat...
395,14818,Customer#000014818,eLgVo2pz5HoO1,8,18-946-218-7449,2793.26,BUILDING,c packages. quickly final braids cajole carefu...
396,14819,Customer#000014819,"w8StIbymUXmLCcUag6sx6LUIp8E3pA,Ux",6,16-769-398-7926,7308.39,AUTOMOBILE,"ss, final asymptotes use furiously slyly ironi..."
397,14881,Customer#000014881,Nt4RURDDeB,9,19-928-603-4563,1001.44,BUILDING,althily ironic platelets wake carefully carefu...
398,14981,Customer#000014981,6oPjckyvvDFZDiBSit7EhS0uAXqLPHWnKn,10,20-961-899-8957,-540.14,HOUSEHOLD,"ronic theodolites above the special, even idea..."

In [22]:
%%sql
-- all customer rows which have nationkey = 10 or nationkey = 20
SELECT * FROM customer WHERE c_nationkey IN (10, 20);

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,6,Customer#000000006,"sKZz0CsnMD7mp4Xd0YrBvx,LREYKUWAh yVn",20,30-114-968-4951,7638.57,AUTOMOBILE,tions. even deposits boost according to the sl...
1,16,Customer#000000016,"cYiaeMLZSMAOQ2 d0W,",10,20-781-609-3107,4681.03,FURNITURE,kly silent courts. thinly regular theodolites ...
2,41,Customer#000000041,IM9mzmyoxeBmvNw8lA7G3Ydska2nkZF,10,20-917-711-4011,270.95,HOUSEHOLD,"ly regular accounts hang bold, silent packages..."
3,49,Customer#000000049,"cNgAeX7Fqrdf7HQN9EwjUa4nxT,68L FKAxzl",10,20-908-631-4424,4573.94,FURNITURE,nusual foxes! fluffily pending packages mainta...
4,55,Customer#000000055,zIRBR4KNEl HzaiV3a i9n6elrxzDEh8r8pDom,10,20-180-440-8525,4572.11,MACHINERY,ully unusual packages wake bravely bold packag...
...,...,...,...,...,...,...,...,...
995,12731,Customer#000012731,"vlgVarjXnWc,gtpfn5oms9qD1AM",20,30-217-649-3797,9198.53,BUILDING,"r instructions are slyly among the ironic, eve"
996,12744,Customer#000012744,"B8waTNvJXdOsqm6wrXWC9,oVJ8JFSCo5ROb",20,30-536-921-9179,7123.50,MACHINERY,uickly unusual dependencies along the quickly ...
997,12746,Customer#000012746,Sy3c2qnORGe05G4QyVJcPvc,20,30-625-211-9755,3241.37,HOUSEHOLD,pinto beans; furiously regular packages are b...
998,12798,Customer#000012798,4i4g8MyvkOzkwCaP5NocPLia0,10,20-238-557-6455,2628.36,AUTOMOBILE,ns nag carefully carefully quick deposits. sly...
999,12803,Customer#000012803,4GfCBnOP4cwNp67uUouyqQosqOMKYkOKXdzKWDb,20,30-782-739-9002,2261.81,FURNITURE,about the ironic platelets. instructions are ...

In [23]:
%%sql 
-- all customer rows which do not have nationkey as 10 or 20
SELECT * FROM customer WHERE c_nationkey NOT IN (10,20);

,c_custkey,c_name,c_address,c_nationkey,c_phone,c_acctbal,c_mktsegment,c_comment
0,1,Customer#000000001,"IVhzIApeRb ot,c,E",15,25-989-741-2988,711.56,BUILDING,"to the even, regular platelets. regular, ironi..."
1,2,Customer#000000002,"XSTf4,NCwDVaWNe6tEgvwfmRchLXak",13,23-768-687-3665,121.65,AUTOMOBILE,l accounts. blithely ironic theodolites integr...
2,3,Customer#000000003,MG9kdTD2WBHm,1,11-719-748-3364,7498.12,AUTOMOBILE,"deposits eat slyly ironic, even instructions...."
3,4,Customer#000000004,XxVSJsLAGtn,4,14-128-190-5944,2866.83,MACHINERY,"requests. final, regular ideas sleep final accou"
4,5,Customer#000000005,KvpyuHCplrB84WgAiGV6sYpZq7Tj,3,13-750-942-6364,794.47,HOUSEHOLD,n accounts will have to unwind. foxes cajole a...
...,...,...,...,...,...,...,...,...
995,1090,Customer#000001090,P2JDHFVxjU,15,25-711-934-6343,5212.43,AUTOMOBILE,ffily even packages wake quickly
996,1091,Customer#000001091,"4ye7wJ3gU92RZCpwTtDi8Ws,",17,27-336-955-4882,-710.53,BUILDING,y. carefully ironic excuses sleep quickly fluf...
997,1092,Customer#000001092,",oAq2L60hjb8",15,25-766-175-4580,2004.15,HOUSEHOLD,carefully silent somas can wake carefully aft
998,1093,Customer#000001093,"LO,9qCPIjSXriBqQsAOXLrQKedQ8UO6gb",24,34-931-911-6156,-273.96,HOUSEHOLD,p furiously carefully bold packages. regular e...
999,1094,Customer#000001094,OFz0eedTmPmXk2 3XM9v9Mcp13NVC0PK,2,12-234-721-9871,2544.49,MACHINERY,tes serve blithely quickly pending foxes. expr...

In [24]:
%%sql 
SELECT COUNT(*) FROM customer;

   count(1)
0     15000

In [25]:
%%sql
SELECT COUNT(*) FROM lineitem;

   count(1)
0    600572

In [26]:
%%sql
-- Will show the first ten customer records with the lowest custkey
-- rows are ordered in ASC order by default
SELECT * FROM orders ORDER BY o_custkey LIMIT 10;

,o_orderkey,o_custkey,o_orderstatus,o_totalprice,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_comment
0,36422,1,O,268835.44,1997-03-04,3-MEDIUM,Clerk#000000532,0,"e evenly final dependencies. regular, bold pin..."
1,224167,1,O,81485.84,1996-05-08,5-LOW,Clerk#000000657,0,s along the carefully special pinto beans cajo...
2,135943,1,F,263247.54,1993-06-22,4-NOT SPECIFIED,Clerk#000000685,0,ies. blithely pending deposits
3,164711,1,F,283261.47,1992-04-26,3-MEDIUM,Clerk#000000361,0,"accounts among the regular,"
4,287619,1,O,11925.85,1996-12-26,5-LOW,Clerk#000000854,0,r requests must sleep carefully furiously regu...
5,385825,1,O,235155.22,1995-11-01,2-HIGH,Clerk#000000465,0,e even foxes. regularly even instructions boos...
6,430243,1,F,35523.05,1994-12-24,4-NOT SPECIFIED,Clerk#000000121,0,n braids among the final packages cajole pendin
7,454791,1,F,83779.26,1992-04-19,1-URGENT,Clerk#000000815,0,uriously ironic deposits wake across the s
8,579908,1,O,45744.09,1996-12-09,5-LOW,Clerk#000000783,0,asymptotes. regular requests boost blithely. ...
9,52263,2,F,36433.77,1994-05-08,4-NOT SPECIFIED,Clerk#000000080,0,"lly ironic, even packages. bold foxes wake car..."

In [27]:
%%sql
-- Will show the first ten customer's records with the highest custkey
SELECT * FROM orders ORDER BY o_custkey DESC LIMIT 10;

,o_orderkey,o_custkey,o_orderstatus,o_totalprice,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_comment
0,134848,14999,O,170212.14,1998-03-07,2-HIGH,Clerk#000000669,0,ccounts. slyly even requests sleep slyly bold ...
1,129605,14999,P,172005.93,1995-03-27,3-MEDIUM,Clerk#000000578,0,s. quickly regular deposits are. slyly sile
2,94817,14999,F,193676.15,1992-08-02,4-NOT SPECIFIED,Clerk#000000650,0,mong the ironic deposits wake carefully quickl...
3,67298,14999,O,296795.91,1995-09-15,1-URGENT,Clerk#000000213,0,nic excuses nag after the pending
4,157894,14999,F,76068.72,1992-06-08,4-NOT SPECIFIED,Clerk#000000952,0,ely regular packages run alongside of the bold...
5,158657,14999,O,164096.58,1998-02-28,3-MEDIUM,Clerk#000000977,0,ess courts haggle quickly final packages-- car...
6,178087,14999,F,320537.50,1994-04-16,5-LOW,Clerk#000000872,0,atelets haggle furiously at the slyly final pa...
7,190498,14999,O,102768.22,1998-03-13,5-LOW,Clerk#000000941,0,at the ironic pinto beans. excuses are. fluffi...
8,215168,14999,F,202248.65,1992-02-24,2-HIGH,Clerk#000000633,0,ages against the busy packag
9,233956,14999,F,219593.16,1994-03-28,5-LOW,Clerk#000000719,0,tructions according to the even deposit

In [34]:
%%sql
SELECT
o.o_orderkey,
l.l_orderkey
FROM orders o
JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY 
AND l.l_shipdate + INTERVAL '5' DAY
LIMIT 10;

   o_orderkey  l_orderkey
0           7           7
1          32          32
2          33          33
3          69          69
4          71          71
5         132         132
6         133         133
7         198         198
8         259         259
9         260         260

In [35]:
%%sql
SELECT
COUNT(o.o_orderkey) AS order_rows_count,
COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
orders o
JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate + INTERVAL '5' DAY;

   order_rows_count  lineitem_rows_count
0             24613                24613

In [37]:
%%sql 
SELECT
o.o_orderkey,
l.l_orderkey,
o.o_orderdate,
l.l_shipdate
FROM 
orders o
LEFT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate + INTERVAL '5' DAY
LIMIT 10;

   o_orderkey  l_orderkey o_orderdate  l_shipdate
0           1         NaN  1996-01-02        None
1           2         NaN  1996-12-01        None
2           3         NaN  1993-10-14        None
3           4         NaN  1995-10-11        None
4           5         NaN  1994-07-30        None
5           6         NaN  1992-02-21        None
6           7         7.0  1996-01-10  1996-01-15
7          32        32.0  1995-07-16  1995-07-21
8          33        33.0  1993-10-27  1993-10-29
9          34         NaN  1998-07-21        None

In [15]:
%%sql
SELECT
COUNT (o.o_orderkey) AS order_rows_count,
COUNT (l.l_orderkey) AS lineitem_rows_count
FROM
orders o
LEFT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate + INTERVAL '5' DAY;

   order_rows_count  lineitem_rows_count
0            151933                24613

In [16]:
%%sql
SELECT
o.o_orderkey, l.l_orderkey
FROM
orders o 
RIGHT JOIN lineitem l ON o.o_orderkey = l.l_orderkey 
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY and l.l_shipdate + INTERVAL '5' DAY
LIMIT 10;

   o_orderkey  l_orderkey
0         NaN           1
1         NaN           1
2         NaN           1
3         NaN           1
4         NaN           1
5         NaN           1
6         NaN           2
7         NaN           3
8         NaN           3
9         NaN           3

In [18]:
%%sql
SELECT
COUNT(o.o_orderkey) AS order_rows_count,
COUNT(l.l_orderkey) AS limititem_rows_count
FROM 
orders o
RIGHT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate + INTERVAL '5' DAY;

   order_rows_count  limititem_rows_count
0             24613                600572

In [20]:
%%sql 
SELECT
o.o_orderkey,
l.l_orderkey,
o.o_orderdate,
l.l_shipdate
FROM
orders o
FULL OUTER JOIN lineitem l ON o.o_orderkey = l.l_orderkey
AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate + INTERVAL '5' DAY
LIMIT 10;

   o_orderkey  l_orderkey o_orderdate  l_shipdate
0         7.0           7  1996-01-10  1996-01-15
1         NaN           7        None  1996-05-07
2         NaN           7        None  1996-02-01
3         NaN           7        None  1996-03-21
4         NaN           7        None  1996-02-11
5         NaN           7        None  1996-01-16
6         NaN           7        None  1996-02-10
7        32.0          32  1995-07-16  1995-07-21
8         NaN          32        None  1995-10-23
9         NaN          32        None  1995-08-14

In [23]:
%%sql
SELECT
  COUNT(o.o_orderkey) AS order_rows_count,
  COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
  orders o
  FULL OUTER JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY;
-- 151933, 600572

   order_rows_count  lineitem_rows_count
0            151933               600572

In [24]:
%%sql
SELECT 
n.n_name AS nation_c_name,
r.r_name AS region_c_name
FROM
nation n
CROSS JOIN region r;

     nation_c_name region_c_name
0          ALGERIA        AFRICA
1          ALGERIA       AMERICA
2          ALGERIA          ASIA
3          ALGERIA        EUROPE
4          ALGERIA   MIDDLE EAST
..             ...           ...
120  UNITED STATES        AFRICA
121  UNITED STATES       AMERICA
122  UNITED STATES          ASIA
123  UNITED STATES        EUROPE
124  UNITED STATES   MIDDLE EAST

[125 rows x 2 columns]

In [30]:
%%sql
SELECT
o1.o_custkey as o1_custkey,
o1.o_totalprice as o1_totalprice,
o1.o_orderdate as o1_orderdate,
o2.o_totalprice as o2_totalprice,
o2.o_orderdate as o2_orderdate
FROM
orders o1
JOIN orders o2 ON o1.o_custkey = o2.o_custkey
AND year(o1.o_orderdate) = year(o2.o_orderdate)
AND weekofyear(o1.o_orderdate) = weekofyear(o2.o_orderdate)
WHERE
o1.o_orderkey != o2.o_orderkey AND o1.o_orderdate < o2.o_orderdate -- I did it like this to show that o1 is the earliest orderdate
LIMIT 10;

   o1_custkey o1_totalprice o1_orderdate o2_totalprice o2_orderdate
0        8177     307811.89   1996-09-20     123887.45   1996-09-22
1        2227      51571.37   1992-01-13      20804.50   1992-01-14
2        8143     228500.69   1992-10-21     171242.00   1992-10-23
3       14374      12079.04   1997-12-24     189512.64   1997-12-27
4        9553     121752.10   1993-01-11      82391.41   1993-01-13
5        4384      60805.58   1996-12-16     216008.71   1996-12-22
6        4711     141214.74   1993-11-09     150068.88   1993-11-12
7        3808     144347.70   1996-03-18     293521.00   1996-03-22
8        7855     145749.93   1995-01-16      76833.08   1995-01-17
9       10405      69641.96   1993-06-29     236514.83   1993-07-01

In [5]:
%%sql
SELECT
o_orderpriority,
COUNT(*) AS num_orders
FROM orders
GROUP BY 
o_orderpriority
ORDER BY
o_orderpriority ASC;

   o_orderpriority  num_orders
0         1-URGENT       30111
1           2-HIGH       30172
2         3-MEDIUM       29563
3  4-NOT SPECIFIED       29910
4            5-LOW       30244

In [9]:
%%sql
SELECT 
o_orderpriority,
COUNT(*) AS num_orders
FROM
orders
GROUP BY
o_orderpriority
HAVING
COUNT(*) > 3000
ORDER BY
num_orders DESC;

   o_orderpriority  num_orders
0            5-LOW       30244
1           2-HIGH       30172
2         1-URGENT       30111
3  4-NOT SPECIFIED       29910
4         3-MEDIUM       29563